name: ci
on: [ push, pull_request ]
jobs:
  ci:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: test
        run: |
          ./gradlew clean test jacocoTestReport integrationTest
          bash <(curl -s https://codecov.io/bash)
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v3
        if: always()
        with:
          report_paths: '**/build/test-results/test/TEST-*.xml'
      - name: detekt
        run: |
          ./gradlew clean detektCheck || true
      - name: validateGradlePlugins
        run: |
          ./gradlew validatePlugins
  cd:
    runs-on: ubuntu-22.04
    needs: ci
    if: ${{ startsWith(github.ref, 'refs/tags/') }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
      - uses: little-core-labs/get-git-tag@v3.0.2
        id: tag
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
      - name: deliver gradle plugin
        run: ./gradlew :marathon-gradle-plugin:publishPlugins -Pgradle.publish.key=$GRADLE_PUBLISH_KEY -Pgradle.publish.secret=$GRADLE_PUBLISH_SECRET -PreleaseMode=RELEASE
        env:
          GRADLE_PUBLISH_KEY: ${{ secrets.GRADLE_PUBLISH_KEY }}
          GRADLE_PUBLISH_SECRET: ${{ secrets.GRADLE_PUBLISH_SECRET }}
